// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0RkCwEf0WgVVOrx4H30MYvSpBwn7tuZU',
    appId: '1:102106082011:web:ba136bdd1c980e76b5bafe',
    messagingSenderId: '102106082011',
    projectId: 'olx-app-gui',
    authDomain: 'olx-app-gui.firebaseapp.com',
    storageBucket: 'olx-app-gui.appspot.com',
    measurementId: 'G-6KD1M9RM1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH5keDgqNzJJjLZLDe3uIJoIyAlXhXyeI',
    appId: '1:102106082011:android:aa74583c823a7328b5bafe',
    messagingSenderId: '102106082011',
    projectId: 'olx-app-gui',
    storageBucket: 'olx-app-gui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrKVgewThpz-EeqSw2nXV3a3g_WyXj7wA',
    appId: '1:102106082011:ios:e6444ac6ac9e19d7b5bafe',
    messagingSenderId: '102106082011',
    projectId: 'olx-app-gui',
    storageBucket: 'olx-app-gui.appspot.com',
    iosClientId: '102106082011-cusoh36938d0hcodcs4iaitj5tvd3kja.apps.googleusercontent.com',
    iosBundleId: 'com.guilhermereisapps.olx',
  );
}
